//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the hre_random_node package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __hre_random_node__HRERANDOMCONFIG_H__
#define __hre_random_node__HRERANDOMCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace hre_random_node
{
  class HreRandomConfigStatics;
  
  class HreRandomConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(HreRandomConfig &config, const HreRandomConfig &max, const HreRandomConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const HreRandomConfig &config1, const HreRandomConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, HreRandomConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const HreRandomConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, HreRandomConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const HreRandomConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T HreRandomConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (HreRandomConfig::* field);

      virtual void clamp(HreRandomConfig &config, const HreRandomConfig &max, const HreRandomConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const HreRandomConfig &config1, const HreRandomConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, HreRandomConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const HreRandomConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, HreRandomConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const HreRandomConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 47 "../cfg/hre_random_alg_config.cfg"
      int op_mode;
//#line 48 "../cfg/hre_random_alg_config.cfg"
      std::string seq_file;
//#line 49 "../cfg/hre_random_alg_config.cfg"
      int home_interval;
//#line 50 "../cfg/hre_random_alg_config.cfg"
      int speech_interval;
//#line 51 "../cfg/hre_random_alg_config.cfg"
      int repeat_interval;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("HreRandomConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const HreRandomConfig &__max__ = __getMax__();
      const HreRandomConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const HreRandomConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const HreRandomConfig &__getDefault__();
    static const HreRandomConfig &__getMax__();
    static const HreRandomConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const HreRandomConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void HreRandomConfig::ParamDescription<std::string>::clamp(HreRandomConfig &config, const HreRandomConfig &max, const HreRandomConfig &min) const
  {
    return;
  }

  class HreRandomConfigStatics
  {
    friend class HreRandomConfig;
    
    HreRandomConfigStatics()
    {
//#line 47 "../cfg/hre_random_alg_config.cfg"
      __min__.op_mode = 0;
//#line 47 "../cfg/hre_random_alg_config.cfg"
      __max__.op_mode = 1;
//#line 47 "../cfg/hre_random_alg_config.cfg"
      __default__.op_mode = 0;
//#line 47 "../cfg/hre_random_alg_config.cfg"
      __param_descriptions__.push_back(HreRandomConfig::AbstractParamDescriptionConstPtr(new HreRandomConfig::ParamDescription<int>("op_mode", "int", 0, "Desired operation mode", "{'enum_description': 'Possible operation modes.', 'enum': [{'srcline': 42, 'description': 'Execute random sequences', 'srcfile': '../cfg/hre_random_alg_config.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Random'}, {'srcline': 43, 'description': 'Execute a given sequence', 'srcfile': '../cfg/hre_random_alg_config.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Sequence'}]}", &HreRandomConfig::op_mode)));
//#line 48 "../cfg/hre_random_alg_config.cfg"
      __min__.seq_file = "";
//#line 48 "../cfg/hre_random_alg_config.cfg"
      __max__.seq_file = "";
//#line 48 "../cfg/hre_random_alg_config.cfg"
      __default__.seq_file = "";
//#line 48 "../cfg/hre_random_alg_config.cfg"
      __param_descriptions__.push_back(HreRandomConfig::AbstractParamDescriptionConstPtr(new HreRandomConfig::ParamDescription<std::string>("seq_file", "str", 0, "Sequence file to execute", "", &HreRandomConfig::seq_file)));
//#line 49 "../cfg/hre_random_alg_config.cfg"
      __min__.home_interval = 2;
//#line 49 "../cfg/hre_random_alg_config.cfg"
      __max__.home_interval = 10;
//#line 49 "../cfg/hre_random_alg_config.cfg"
      __default__.home_interval = 3;
//#line 49 "../cfg/hre_random_alg_config.cfg"
      __param_descriptions__.push_back(HreRandomConfig::AbstractParamDescriptionConstPtr(new HreRandomConfig::ParamDescription<int>("home_interval", "int", 0, "Desired interval (in cicles) to execute the home sequence", "", &HreRandomConfig::home_interval)));
//#line 50 "../cfg/hre_random_alg_config.cfg"
      __min__.speech_interval = 1;
//#line 50 "../cfg/hre_random_alg_config.cfg"
      __max__.speech_interval = 10;
//#line 50 "../cfg/hre_random_alg_config.cfg"
      __default__.speech_interval = 1;
//#line 50 "../cfg/hre_random_alg_config.cfg"
      __param_descriptions__.push_back(HreRandomConfig::AbstractParamDescriptionConstPtr(new HreRandomConfig::ParamDescription<int>("speech_interval", "int", 0, "Desired interval (in cicles) to speak", "", &HreRandomConfig::speech_interval)));
//#line 51 "../cfg/hre_random_alg_config.cfg"
      __min__.repeat_interval = 1;
//#line 51 "../cfg/hre_random_alg_config.cfg"
      __max__.repeat_interval = 10;
//#line 51 "../cfg/hre_random_alg_config.cfg"
      __default__.repeat_interval = 3;
//#line 51 "../cfg/hre_random_alg_config.cfg"
      __param_descriptions__.push_back(HreRandomConfig::AbstractParamDescriptionConstPtr(new HreRandomConfig::ParamDescription<int>("repeat_interval", "int", 0, "Minimum interval (in cicles) between two identical motion sequences", "", &HreRandomConfig::repeat_interval)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<HreRandomConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<HreRandomConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    HreRandomConfig __max__;
    HreRandomConfig __min__;
    HreRandomConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const HreRandomConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static HreRandomConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &HreRandomConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const HreRandomConfig &HreRandomConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const HreRandomConfig &HreRandomConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const HreRandomConfig &HreRandomConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<HreRandomConfig::AbstractParamDescriptionConstPtr> &HreRandomConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const HreRandomConfigStatics *HreRandomConfig::__get_statics__()
  {
    const static HreRandomConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = HreRandomConfigStatics::get_instance();
    
    return statics;
  }

//#line 42 "../cfg/hre_random_alg_config.cfg"
      const int HreRandom_Random = 0;
//#line 43 "../cfg/hre_random_alg_config.cfg"
      const int HreRandom_Sequence = 1;
}

#endif // __HRERANDOMRECONFIGURATOR_H__
