(cl:defpackage iri_wam_arm_navigation-msg
  (:use )
  (:export
   "<SIMPLEPOSEGOAL>"
   "SIMPLEPOSEGOAL"
   "<SIMPLEPOSEACTIONRESULT>"
   "SIMPLEPOSEACTIONRESULT"
   "<SIMPLEPOSEACTIONGOAL>"
   "SIMPLEPOSEACTIONGOAL"
   "<SIMPLEPOSEFEEDBACK>"
   "SIMPLEPOSEFEEDBACK"
   "<SIMPLEPOSERESULT>"
   "SIMPLEPOSERESULT"
   "<SIMPLEPOSEACTION>"
   "SIMPLEPOSEACTION"
   "<SIMPLEPOSEACTIONFEEDBACK>"
   "SIMPLEPOSEACTIONFEEDBACK"
  ))

