TrajectoryPlannerROS:
  controller_frequency: 5
  max_vel_x: 0.3
  min_vel_x: 0.1
  

  sim_time: 3
  sim_granurality: 0.08
  penalize_negative_x: false
  escape_vel: -0.2
  stop_time_buffer: 0.4


  vx_samples: 5
  vtheta_samples: 20

  path_distance_bias: 0.1
  goal_distance_bias: 0.4
  occdist_scale: 0.1

  holonomic_robot: false
  dwa: true
