/* Auto-generated by genmsg_cpp for file /home/irojas/iri-ros-pkg/iri_wam/iri_wam_arm_navigation/msg/SimplePoseFeedback.msg */
#ifndef IRI_WAM_ARM_NAVIGATION_MESSAGE_SIMPLEPOSEFEEDBACK_H
#define IRI_WAM_ARM_NAVIGATION_MESSAGE_SIMPLEPOSEFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace iri_wam_arm_navigation
{
template <class ContainerAllocator>
struct SimplePoseFeedback_ {
  typedef SimplePoseFeedback_<ContainerAllocator> Type;

  SimplePoseFeedback_()
  : succesed(false)
  {
  }

  SimplePoseFeedback_(const ContainerAllocator& _alloc)
  : succesed(false)
  {
  }

  typedef uint8_t _succesed_type;
  uint8_t succesed;


private:
  static const char* __s_getDataType_() { return "iri_wam_arm_navigation/SimplePoseFeedback"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d174ccd3308b564587c021fd57717187"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Result Definition\n\
bool succesed\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, succesed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, succesed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(succesed);
    return size;
  }

  typedef boost::shared_ptr< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SimplePoseFeedback
typedef  ::iri_wam_arm_navigation::SimplePoseFeedback_<std::allocator<void> > SimplePoseFeedback;

typedef boost::shared_ptr< ::iri_wam_arm_navigation::SimplePoseFeedback> SimplePoseFeedbackPtr;
typedef boost::shared_ptr< ::iri_wam_arm_navigation::SimplePoseFeedback const> SimplePoseFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace iri_wam_arm_navigation

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d174ccd3308b564587c021fd57717187";
  }

  static const char* value(const  ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd174ccd3308b5645ULL;
  static const uint64_t static_value2 = 0x87c021fd57717187ULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "iri_wam_arm_navigation/SimplePoseFeedback";
  }

  static const char* value(const  ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Result Definition\n\
bool succesed\n\
\n\
\n\
";
  }

  static const char* value(const  ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.succesed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SimplePoseFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::iri_wam_arm_navigation::SimplePoseFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "succesed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succesed);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IRI_WAM_ARM_NAVIGATION_MESSAGE_SIMPLEPOSEFEEDBACK_H

