/* Auto-generated by genmsg_cpp for file /home/irojas/ros/iri-ros-pkg/iri_wam/iri_wam_controllers/msg/PathDuration.msg */
#ifndef IRI_WAM_CONTROLLERS_MESSAGE_PATHDURATION_H
#define IRI_WAM_CONTROLLERS_MESSAGE_PATHDURATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace iri_wam_controllers
{
template <class ContainerAllocator>
struct PathDuration_ {
  typedef PathDuration_<ContainerAllocator> Type;

  PathDuration_()
  : header()
  , duration_path_expected()
  {
  }

  PathDuration_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , duration_path_expected()
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef ros::Duration _duration_path_expected_type;
  ros::Duration duration_path_expected;


private:
  static const char* __s_getDataType_() { return "iri_wam_controllers/PathDuration"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "fd865e85cc346994ac32a0d0a54b9778"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
duration duration_path_expected\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, duration_path_expected);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, duration_path_expected);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(duration_path_expected);
    return size;
  }

  typedef boost::shared_ptr< ::iri_wam_controllers::PathDuration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_wam_controllers::PathDuration_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PathDuration
typedef  ::iri_wam_controllers::PathDuration_<std::allocator<void> > PathDuration;

typedef boost::shared_ptr< ::iri_wam_controllers::PathDuration> PathDurationPtr;
typedef boost::shared_ptr< ::iri_wam_controllers::PathDuration const> PathDurationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::iri_wam_controllers::PathDuration_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::iri_wam_controllers::PathDuration_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace iri_wam_controllers

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::iri_wam_controllers::PathDuration_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::iri_wam_controllers::PathDuration_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::iri_wam_controllers::PathDuration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fd865e85cc346994ac32a0d0a54b9778";
  }

  static const char* value(const  ::iri_wam_controllers::PathDuration_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfd865e85cc346994ULL;
  static const uint64_t static_value2 = 0xac32a0d0a54b9778ULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_wam_controllers::PathDuration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "iri_wam_controllers/PathDuration";
  }

  static const char* value(const  ::iri_wam_controllers::PathDuration_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::iri_wam_controllers::PathDuration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
duration duration_path_expected\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::iri_wam_controllers::PathDuration_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::iri_wam_controllers::PathDuration_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::iri_wam_controllers::PathDuration_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::iri_wam_controllers::PathDuration_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.duration_path_expected);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PathDuration_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_wam_controllers::PathDuration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::iri_wam_controllers::PathDuration_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "duration_path_expected: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.duration_path_expected);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IRI_WAM_CONTROLLERS_MESSAGE_PATHDURATION_H

