; Auto-generated. Do not edit!


(cl:in-package iri_wam_arm_navigation-msg)


;//! \htmlinclude SimplePoseGoal.msg.html

(cl:defclass <SimplePoseGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped))
   (frame_id
    :reader frame_id
    :initarg :frame_id
    :type cl:string
    :initform ""))
)

(cl:defclass SimplePoseGoal (<SimplePoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SimplePoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SimplePoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name iri_wam_arm_navigation-msg:<SimplePoseGoal> is deprecated: use iri_wam_arm_navigation-msg:SimplePoseGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <SimplePoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader iri_wam_arm_navigation-msg:goal-val is deprecated.  Use iri_wam_arm_navigation-msg:goal instead.")
  (goal m))

(cl:ensure-generic-function 'frame_id-val :lambda-list '(m))
(cl:defmethod frame_id-val ((m <SimplePoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader iri_wam_arm_navigation-msg:frame_id-val is deprecated.  Use iri_wam_arm_navigation-msg:frame_id instead.")
  (frame_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SimplePoseGoal>) ostream)
  "Serializes a message object of type '<SimplePoseGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'frame_id))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'frame_id))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SimplePoseGoal>) istream)
  "Deserializes a message object of type '<SimplePoseGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'frame_id) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'frame_id) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SimplePoseGoal>)))
  "Returns string type for a message object of type '<SimplePoseGoal>"
  "iri_wam_arm_navigation/SimplePoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SimplePoseGoal)))
  "Returns string type for a message object of type 'SimplePoseGoal"
  "iri_wam_arm_navigation/SimplePoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SimplePoseGoal>)))
  "Returns md5sum for a message object of type '<SimplePoseGoal>"
  "5524b806d455135dc4ee6eb0f2ce299b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SimplePoseGoal)))
  "Returns md5sum for a message object of type 'SimplePoseGoal"
  "5524b806d455135dc4ee6eb0f2ce299b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SimplePoseGoal>)))
  "Returns full string definition for message of type '<SimplePoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal Definition~%geometry_msgs/PoseStamped goal~%string frame_id # This is the name of link to move, and not necessary is the same frame_id of PoseStamped~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SimplePoseGoal)))
  "Returns full string definition for message of type 'SimplePoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal Definition~%geometry_msgs/PoseStamped goal~%string frame_id # This is the name of link to move, and not necessary is the same frame_id of PoseStamped~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SimplePoseGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
     4 (cl:length (cl:slot-value msg 'frame_id))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SimplePoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SimplePoseGoal
    (cl:cons ':goal (goal msg))
    (cl:cons ':frame_id (frame_id msg))
))
