; Auto-generated. Do not edit!


(cl:in-package iri_wam_arm_navigation-msg)


;//! \htmlinclude SimplePoseFeedback.msg.html

(cl:defclass <SimplePoseFeedback> (roslisp-msg-protocol:ros-message)
  ((succesed
    :reader succesed
    :initarg :succesed
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SimplePoseFeedback (<SimplePoseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SimplePoseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SimplePoseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name iri_wam_arm_navigation-msg:<SimplePoseFeedback> is deprecated: use iri_wam_arm_navigation-msg:SimplePoseFeedback instead.")))

(cl:ensure-generic-function 'succesed-val :lambda-list '(m))
(cl:defmethod succesed-val ((m <SimplePoseFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader iri_wam_arm_navigation-msg:succesed-val is deprecated.  Use iri_wam_arm_navigation-msg:succesed instead.")
  (succesed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SimplePoseFeedback>) ostream)
  "Serializes a message object of type '<SimplePoseFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'succesed) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SimplePoseFeedback>) istream)
  "Deserializes a message object of type '<SimplePoseFeedback>"
    (cl:setf (cl:slot-value msg 'succesed) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SimplePoseFeedback>)))
  "Returns string type for a message object of type '<SimplePoseFeedback>"
  "iri_wam_arm_navigation/SimplePoseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SimplePoseFeedback)))
  "Returns string type for a message object of type 'SimplePoseFeedback"
  "iri_wam_arm_navigation/SimplePoseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SimplePoseFeedback>)))
  "Returns md5sum for a message object of type '<SimplePoseFeedback>"
  "d174ccd3308b564587c021fd57717187")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SimplePoseFeedback)))
  "Returns md5sum for a message object of type 'SimplePoseFeedback"
  "d174ccd3308b564587c021fd57717187")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SimplePoseFeedback>)))
  "Returns full string definition for message of type '<SimplePoseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result Definition~%bool succesed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SimplePoseFeedback)))
  "Returns full string definition for message of type 'SimplePoseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result Definition~%bool succesed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SimplePoseFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SimplePoseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SimplePoseFeedback
    (cl:cons ':succesed (succesed msg))
))
