joints:
    [j1,j2,j3,j4,j5,j6,j7]   
constraints:
    goal_time: 0.6
    j1:
        goal: 0.02
    j2:
        goal: 0.02 
    j3:
        goal: 0.02   
    j4:
        goal: 0.02   
    j5:
        goal: 0.02   
    j6:
        goal: 0.02
    j7:
        goal: 0.02   

