# LAST EDITION: jrivero

global_costmap:

# The global frame for the costmap to operate in.
  global_frame: /teo/odom

# The name of the frame for the base link of the robot.
  robot_base_frame: /teo/base_footprint

# The frequency in Hz for the map to be updated.
  update_frequency: 5.0

# The frequency in Hz for the map to be publish display information.
  publish_frequency: 2.0

# Whether or not to use the static map to initialize the costmap. 
# If the rolling_window parameter is set to true, this parameter must be set to false.  
  static_map: false

# Whether or not to use a rolling window version of the costmap. 
# If the static_map parameter is set to true, this parameter must be set to false.
  rolling_window: true

# The width &height of the map in meters.  
  width: 10.0
  height: 10.0

# The resolution of the map in meters/cell.  
  resolution: 0.05
