#Goal Definition
geometry_msgs/PoseStamped goal
string frame_id # This is the name of link to move, and not necessary is the same frame_id of PoseStamped
---
#Result Definition
# An error code reflecting what went wrong
arm_navigation_msgs/ArmNavigationErrorCodes error_code
---
#Feedback Definition
bool succesed
string state
